# -*- coding: utf-8 -*-
"""Aula3LPC1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g42KH5N_jJEOfolKujV1zche8AGUplyr
"""

# ETE PORTO DIGITAL 
# DISCIPLINA : LPC1
# PROFESSOR: CLOVES
# ESTUDANTE : LUANA 

print ('Olá, ETE Porto Digital' )