# -*- coding: utf-8 -*-
"""AULA4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lbnxKZgjKBiEnxRYTSsQca5-Xi-7BKwQ
"""

# ETE PORTO DIGITAL
# PROFESSOR CLOVES ROCHA
# ESTUDANTE: LUANA VITÓRIA 
nomes = [ 'Pedro' , 'João' , 'Leticia' ]
for n in nomes:
 print(n)